-- Create tables
CREATE TABLE customers (
                           id BIGINT AUTO_INCREMENT PRIMARY KEY,
                           username VARCHAR(255) UNIQUE NOT NULL,
                           password VARCHAR(255) NOT NULL
);

CREATE TABLE CustomerTransactions (
                                       id BIGINT AUTO_INCREMENT PRIMARY KEY,
                                       customer_id BIGINT,
                                       spend_details VARCHAR(255),
                                       amount DECIMAL(10, 2) NOT NULL,
                                       date DATE NOT NULL,
                                       FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE TABLE customer_points
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY ,
    customer_id BIGINT,
    points      INT,
    "month"     INT,
    "year"      INT
);

-- Insert dummy data
INSERT INTO customers (username, password) VALUES
                                               ('Ram', 'password123'),
                                               ('Riya', 'mypassword');

INSERT INTO CustomerTransactions (customer_id, spend_details, amount, date) VALUES
                                                                  (1, 'Shopping',120.50, '2024-06-15'),
                                                                  (1, 'Food',75.00, '2024-07-20'),
                                                                  (2, 'Shopping',55.00, '2024-06-25'),
                                                                  (2, 'Hosptial', 95.00, '2024-07-05');

INSERT INTO customer_points (customer_id, points,"month","year") VALUES
                                                                   (1, 6, 2024, 42),
                                                                   (1, 7, 2024, 15),
                                                                   (2, 6, 2024, 6),
                                                                   (2, 7, 2024, 9);
